### ISSUE TITLE
app not responding timeout while opening connection

### ISSUE THREAD

**Issue by geeksville** [geeksville/Gaggle#9]
DALVIK THREADS:
"main" prio=5 tid=1 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x4001d8d8 self=0xccc8
  | sysTid=20578 nice=0 sched=0/0 cgrp=default handle=-1345013672
  | schedstat=( 22034202241 23076386333 21279 )
  at org.apache.harmony.luni.platform.OSNetworkSystem.connectStreamWithTimeoutSocketImpl(Native Method)
  at org.apache.harmony.luni.platform.OSNetworkSystem.connect(OSNetworkSystem.java:115)
  at org.apache.harmony.luni.net.PlainSocketImpl.connect(PlainSocketImpl.java:244)
  at org.apache.harmony.luni.net.PlainSocketImpl.connect(PlainSocketImpl.java:533)
  at java.net.Socket.connect(Socket.java:1055)
  at org.apache.harmony.luni.internal.net.www.protocol.http.HttpConnection.<init>(HttpConnection.java:62)
  at org.apache.harmony.luni.internal.net.www.protocol.http.HttpConnectionPool.get(HttpConnectionPool.java:88)
  at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getHTTPConnection(HttpURLConnectionImpl.java:927)
  at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:909)
  at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:1152)
  at java.net.URL.openStream(URL.java:653)
  at com.geeksville.location.LeonardoLiveWriter.doLogin(LeonardoLiveWriter.java:210)
  at com.geeksville.location.LeonardoLiveWriter.<init>(LeonardoLiveWriter.java:117)
  at com.geeksville.gaggle.LoggingControl.startLogging(LoggingControl.java:372)
  at com.geeksville.gaggle.LoggingControl.access$1(LoggingControl.java:348)
  at com.geeksville.gaggle.LoggingControl$2.onClick(LoggingControl.java:259)
  at android.view.View.performClick(View.java:2408)
  at android.view.View$PerformClick.run(View.java:8818)
  at android.os.Handler.handleCallback(Handler.java:587)
  at android.os.Handler.dispatchMessage(Handler.java:92)
  at android.os.Looper.loop(Looper.java:123)
  at android.app.ActivityThread.main(ActivityThread.java:4627)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:521)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
  at dalvik.system.NativeStart.main(Native Method)

**Comment by geeksville** [comment]
fixed in 0.81
